version: '3'
services:
  seed-node:
    image: "datastax/dse-server"
    environment:
      - DS_LICENSE=accept
      - JVM_EXTRA_OPTS=-Xms1g -Xmx4g
    # Allow DSE to lock memory with mlock
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - 9042:9042
  node:
    image: "datastax/dse-server"
    environment:
      - DS_LICENSE=accept
      - JVM_EXTRA_OPTS=-Xms1g -Xmx4g
      - SEEDS=seed-node
    depends_on:
      - seed-node
    # Allow DSE to lock memory with mlock
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
  studio:
    image: "datastax/dse-studio"
    environment:
      - DS_LICENSE=accept
      - JVM_EXTRA_OPTS=-Xms512m -Xmx1g
    ports:
      - 9091:9091
