INSERT INTO measurement_result JSON '{
    "sensor_id" : "99051fe9-6a9c-46c2-b949-38ef78858dd0",
    "sensor_name" : "Raymond",
    "measurement_time" : "2017-01-01 08:00:00",
    "sensor_location" : {
        "longitude" : 40.4240,
        "latitude": 86.9290
    },
    "measurement": {
        "temperature": 10.5,
        "pressure": 1015.2,
        "humidity": 41,
        "caqi": 75,
        "pm25": 18,
        "pm10": 20
    }
}';
